apiVersion: v1
kind: ServiceAccount
metadata:
  name: memcached-operator-post-install-job
  namespace: memcached-operator-system
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: memcached-operator-post-install-job-role-binding
subjects:
  - kind: ServiceAccount
    name: memcached-operator-post-install-job
    namespace: memcached-operator-system
roleRef:
  kind: ClusterRole
  name: memcached-operator-post-install-job-role
  apiGroup: rbac.authorization.k8s.io